# Generated by Django 5.2.8 on 2025-12-04 16:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ganaderia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoSanitario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('diagnostico', models.CharField(max_length=255)),
                ('tratamiento', models.TextField()),
                ('sintomas', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=255)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Inseminacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('tipo_semen', models.CharField(max_length=100)),
                ('inseminador', models.CharField(max_length=200)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ganaderia.animal')),
                ('responsable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConfirmacionGestacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_confirmacion', models.DateField()),
                ('metodo_diagnostico', models.CharField(max_length=100)),
                ('resultado', models.CharField(choices=[('gestante', 'Gestación Confirmada'), ('negativa', 'No Gestante')], max_length=20)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('responsable', models.CharField(max_length=255)),
                ('inseminacion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='salud.inseminacion')),
            ],
        ),
    ]
