# Generated by Django 5.2.8 on 2025-11-21 01:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finca', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('numero_arete', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(blank=True, max_length=100)),
                ('fecha_nacimiento', models.DateField(blank=True, null=True)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=10)),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('vendido', 'Vendido'), ('muerto', 'Muerto'), ('trasladado', 'Trasladado'), ('inactivo', 'Inactivo')], default='activo', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='animales', to='finca.finca')),
                ('madre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='crias', to='ganaderia.animal')),
            ],
            options={
                'verbose_name': 'Animal',
                'verbose_name_plural': 'Animales',
                'ordering': ['numero_arete'],
            },
        ),
        migrations.CreateModel(
            name='EventoSalida',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('tipo_evento', models.CharField(choices=[('venta', 'Venta'), ('muerte', 'Muerte'), ('descarte', 'Descarte')], max_length=30)),
                ('observaciones', models.TextField(blank=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='eventos_salida', to='ganaderia.animal')),
                ('responsable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Evento de Salida',
                'verbose_name_plural': 'Eventos de Salida',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Parto',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha_nacimiento', models.DateField()),
                ('peso', models.FloatField(blank=True, null=True)),
                ('raza', models.CharField(blank=True, max_length=100)),
                ('sexo', models.CharField(choices=[('M', 'Macho'), ('F', 'Hembra')], max_length=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nacimiento_parto', to='ganaderia.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='finca.finca')),
                ('madre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='partos', to='ganaderia.animal')),
            ],
            options={
                'verbose_name': 'Parto',
                'verbose_name_plural': 'Partos',
                'ordering': ['-fecha_nacimiento'],
            },
        ),
        migrations.CreateModel(
            name='Pesaje',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('peso', models.FloatField()),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pesajes', to='ganaderia.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pesajes', to='finca.finca')),
            ],
            options={
                'verbose_name': 'Pesaje',
                'verbose_name_plural': 'Pesajes',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ProduccionLeche',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('peso_am', models.FloatField(blank=True, null=True)),
                ('peso_pm', models.FloatField(blank=True, null=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producciones', to='ganaderia.animal')),
                ('finca', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='producciones', to='finca.finca')),
            ],
            options={
                'verbose_name': 'Producción de Leche',
                'verbose_name_plural': 'Producción de Leche',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados', to='ganaderia.animal')),
                ('finca_destino', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_destino', to='finca.finca')),
                ('finca_origen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='traslados_origen', to='finca.finca')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Traslado',
                'verbose_name_plural': 'Traslados',
                'ordering': ['-fecha'],
            },
        ),
    ]
