# Generated by Django 5.2.8 on 2025-11-18 01:04
from django.db import migrations

def create_empresas(apps, schema_editor):
    Empresa = apps.get_model('users', 'Empresa')

    empresas = [
        "Agrotiquiza SA",
        "Inversiones Herrago SA",
        "Agroindustrial Las Mercedes SAS",
    ]

    for nombre in empresas:
        Empresa.objects.get_or_create(nombre=nombre)

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_empresas),
    ]

